#compilacion
pool:
  vmImage: ubuntu-latest

steps:
#construccion con gradle
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

#integracion de sonarcloud
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar'
    organization: 'example-devsecops'
    projectKey: 'Example-devsecops_pet-clinic-v3'
    projectName: 'pet-clinic-v3'

#ejecucion gradle
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sonarqube'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: true
    sqGradlePluginVersionChoice: 'specify'
    sonarQubeGradlePluginVersion: '3.3'